In [1]:
import numpy as np


In [ ]:
zero=np.zeros(10)
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
one=np.ones(10)
one

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
five=np.ones(10)*5
five

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [5]:
arr=np.array(range(10,50))
arr


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [6]:
Evenarr=np.array(range(10,50,2))
Evenarr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [7]:
a1=np.array([[0,1,2],[3,4,5],[6,7,8]])
a1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
a1=np.array([[1,0,0],[0,1,0],[0,0,1]])
a1

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [10]:
array=np.random.random(1)
array

array([0.00353811])

In [11]:
aaray=np.random.random(25)
aaray


array([0.66156352, 0.10648513, 0.66260284, 0.71746835, 0.41294222,
       0.45315017, 0.61921592, 0.81775533, 0.86911384, 0.2094491 ,
       0.03931959, 0.01686183, 0.58650184, 0.98488122, 0.39641056,
       0.40503984, 0.85607842, 0.75711709, 0.6970331 , 0.07815168,
       0.61039393, 0.19263612, 0.95509059, 0.75412875, 0.85683598])

In [12]:
arr=np.array([np.linspace(0,1)])
arr

array([[0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
        0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
        0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
        0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
        0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
        0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
        0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
        0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
        0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
        0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ]])

In [13]:
ar=np.array([np.linspace(0,1,20)])
ar

array([[0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
        0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
        0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
        0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ]])

In [14]:
e=np.array(range(1,26))
g=e.reshape(5,5)
g

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [15]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [16]:
l=g[2::,1::]
l

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [17]:
l[1,3]

20

In [18]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [19]:
r=g[0:3:,1]
r=r.reshape(3,1)
r

array([[ 2],
       [ 7],
       [12]])

In [20]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE


In [21]:
k=g[4,0:5]
k

array([21, 22, 23, 24, 25])

In [22]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [23]:
k=g[3:5,0:5]
k


array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [24]:
g.sum()

325

In [25]:
g.std()


7.211102550927978

In [26]:
g.sum(axis =0)


array([55, 60, 65, 70, 75])